### ISSUE TITLE
[help] purpose of defroutes

### ISSUE THREAD

**Issue by jtmarmon** [metosin/compojure-api#109]
I'm not quite grepping from the example code what the purpose of defroutes is.

```clj
(defroutes* legacy-route
  (GET* "/legacy/:value" [value]
    (ok {:value value})))

(defapi app
  (swagger-ui)
  (swagger-docs 
    {:info {:title "Sample api"}})
  (context* "/api" []
    :tags ["thingie"]

    (GET* "/plus" []
      :return       Long
      :query-params [x :- Long, {y :- Long 1}]
      :summary      "x+y with query-parameters. y defaults to 1."
      (ok (+ x y)))

    legacy-route
...
```

couldn't you just put 

```clj
  (GET* "/legacy/:value" [value]
    (ok {:value value}))
```

under the `context` without needing the `defroutes*` there? Is `defroutes*` just an alias for a list of routes o_O

**Comment by Deraen** [comment]
> Is defroutes* just an alias for a list of routes o_O 

Yes. If is useful for use cases where you want to split your routes to multiple namespaces.

**Comment by jtmarmon** [comment]
ah, cool. thanks!

**Comment by ikitommi** [comment]
Yeah, the actual runtime (Compojure) routing normally works without `defroutes*`, but the in order to generate the Swagger api docs, we need to access the source code of the routes. `defroutes*` puts source code of it's contents as meta-data so it's accessible in the macro compilation phase.

See https://github.com/metosin/compojure-api/blob/master/src/compojure/api/core.clj#L70
