### ISSUE TITLE
extra slash in swagger request url path

### ISSUE THREAD

**Issue by jtmarmon** [metosin/compojure-api#110]
for some reason the swagger-ui is adding an extra '/' in the url path for api testing causing the test request to 404. when I remove the slash it works fine. The url looks like so: 

`http://localhost:3000//api/foo/bar`

my api is defined as such:

```clj
(defapi app
  (swagger-ui)
  (swagger-docs {...})
  (context* "/api" []
     :tags ["cool api"]
      routes))))```

where routes is a `defroutes*` defined elsewhere.

**Comment by ikitommi** [comment]
Haven't bumped into this. What is the `basePath` in the generated swagger.json? Are you running the app under a servlet container?

**Comment by jtmarmon** [comment]
the basePath is '/'

i'm running the server via `lein ring server`

**Comment by ikitommi** [comment]
I tried with vanilla `lein new compojure-api app` with both `0.20.4` and `0.21.0-SNAPSHOT` of compojure-api and works ok. What versions of the libs are you using? Are you using `ring-swagger-ui` or a npm/webjars-based build of the swagger-ui?

Can you provide a sample non-working project as a gist (files)?

**Comment by jtmarmon** [comment]
so I just ran `lein new compojure-api app` and did `lein ring server` and am having the same issue..
![image](https://cloud.githubusercontent.com/assets/4528076/7820442/8261ffe4-03b6-11e5-9580-be3298f7f550.png)

**Comment by ikitommi** [comment]
could you paste the output of the swagger.json here? Try to figure out what's happening here.

**Comment by ikitommi** [comment]
when in run `lein new compojure-api app` and `lein ring server` everything works ok and https://gist.githubusercontent.com/ikitommi/8f561abe45ec0c78c628/raw/bb9d989cd4c5b661dd2bb83f537e3a9e1244ae18/swagger.json gets generated. You can paste the url into your view of the swagger-ui and see if there is extra slash.

**Comment by jtmarmon** [comment]
https://gist.github.com/jtmarmon/b9d43ea96f65f80dbff8

using your swagger.json still generates an extra slash
![image](https://cloud.githubusercontent.com/assets/4528076/7822923/be472344-03c6-11e5-937f-f951355e1da0.png)

**Comment by ikitommi** [comment]
Your `swagger.json` is ok, works on my machine, so the problem is not on compojure-api side, but on your version of the swagger-ui. Either:

a) for some reason, you have a broken ring-swagger-ui installed
b) your browser & javascript is incompatible with the swagger-ui
c) there is a bug in ring-swagger-ui packaging

=> try the http://petstore.swagger.io/ with your gist url https://gist.githubusercontent.com/jtmarmon/b9d43ea96f65f80dbff8/raw/528dd167360761f9034e5c3289643817a8e07d98/gistfile1.js. If you still see the double slash, write a issue to https://github.com/swagger-api/swagger-ui/issues and link it to this.

if that version works, clean the local maven repo to reinstall all artefacts:

```bash
cd .m2/repository
rm -rf metosin
```

and try again. hope this helps.

**Comment by jtmarmon** [comment]
yup, solved it! thanks for the help :)
