### ISSUE TITLE
Inline descriptions have lots of whitespace which Markdown tries to interpret

### ISSUE THREAD

**Issue by MichaelBlume** [metosin/compojure-api#132]
If I have a multiline description in a route, chances are it's indented at the same level as the route. The clojure reader interprets this as lots of whitespace in the middle of the literal. Markdown then interprets this as blocks of indented text that should not be reformatted. I've introduced the following hack in my own projects, which solves the problem, but I'm curious what others have done.

```clj

(defn indented? [l]
  (contains? #{\space nil} (first l)))

(defn remove-space [l]
  (if (= \space (first l))
    (subs l 1)
    l))

(defn de-indent [s]
  (s/join
    \newline
    (loop [lines (s/split-lines s)]
      (if (every? indented? (rest lines))
        (recur (map remove-space lines))
        lines))))

;; override built-in
(defmethod restructure-param :description [k v acc]
  (update-in acc [:parameters] assoc k (de-indent v)))
```

**Comment by ikitommi** [comment]
Haven't used the long descriptions, but see the challenge with the current implementations. As `:description` allows https://help.github.com/articles/github-flavored-markdown/ I guess the leading spaces do count (for code snipplets).

**Comment by Deraen** [comment]
Not sure if `:description` allows code but if it does, concatenating strings should help:
```
(GET* "/foo" []
  :description (str "first line\n"
                    "foobar")
  ...)
```

**Comment by psarando** [comment]
`:description` does allow code (I think the old `:notes` did not). I just experimented with this in our project and it works nicely: https://github.com/iPlantCollaborativeOpenSource/DiscoveryEnvironmentBackend/commit/f448e4cc03d23d057bcdc1e852ab7459ea5ed560

The extra whitespace usually only affects docs that are separated by blank lines. We have routes that only have 1 paragraph descriptions, so we indent those at the route level, and the extra whitespace is ignored by the markdown parser: https://github.com/iPlantCollaborativeOpenSource/DiscoveryEnvironmentBackend/blob/f448e4cc03d23d057bcdc1e852ab7459ea5ed560/services/metadactyl-clj/src/metadactyl/routes/apps.clj

We have other routes where we take advantage of the markdown parsing to add additional headings with "code" blocks under them: https://github.com/iPlantCollaborativeOpenSource/DiscoveryEnvironmentBackend/blob/f448e4cc03d23d057bcdc1e852ab7459ea5ed560/services/data-info/src/data_info/routes/data.clj#L15-L32
In these routes we keep the entire documentation strings un-indented so it's easier to see how the markdown is formatted, and it looks OK to us because it's similar to HEREDOC formatting.

**Comment by ikitommi** [comment]
I believe this can be closed.
