### ISSUE TITLE
basePath is ignored

### ISSUE THREAD

**Issue by thomaswhitcomb** [metosin/compojure-api#134]
I can't seem to override the basePath within the (swagger-docs).  I can override the :host but the basePath never gets changed.

Here is a snippet of my code:

(swag/defapi
  super-routes
  {:formats [:json] }
  (swag/swagger-ui )
  (swag/swagger-docs
    {:swagger "2.0" :host "somehost" :basePath "/holycow"  :info {:title "my service" } }
    {:tags [{:name "V1", :description "MVP"},{:name "Health", :description "Monitoring"}]})
  (swag/context*
    "/v0"
    []
    :tags ["V0"]
    (swag/PUT*

Is this a bug?

**Comment by ikitommi** [comment]
yes, that's a bug and the root cause is here: https://github.com/metosin/compojure-api/blob/master/src/compojure/api/swagger.clj#L312-L313 <-- we merge the default `:basePath` last to the swagger-data, which overrides any given value. Changing the order of the two lines should fix this. Would you like to create a Pull Request of this?

PS: the default `:basePath` get value here: https://github.com/metosin/ring-swagger/blob/master/src/ring/swagger/core.clj#L225

**Comment by thomaswhitcomb** [comment]
Yup, I'll start on it now.

**Comment by ikitommi** [comment]
released `0.22.1` which has your fix (and the validation error typo fixed ). Thanks again!

**Comment by thomaswhitcomb** [comment]
Thanks for the fast turnaround!
