### ISSUE TITLE
How to define a param that starts with a number?

### ISSUE THREAD

**Issue by kanwei** [metosin/compojure-api#322]
I have a parameter name that starts with a number, and because the *-params take clojure symbols, I can't seem to make the following work:

```
:body-params [360_public_key :- spec/string?
                    url :- spec/string?] #_[webhook ::webhook]
```

Suggestions?

**Comment by ikitommi** [comment]
Hi. You can use `:body` which does `let`-binding. Something like: `:body
[body {:360_public_key string?, :url string?}`. Sets the whole body into
`body`.

6.7.2017 11.00 "Kanwei Li" <notifications@github.com> kirjoitti:

I have a parameter name that starts with a number, and because the *-params
take clojure symbols, I can't seem to make the following work:

:body-params [360_public_key :- spec/string?
                    url :- spec/string?] #_[webhook ::webhook]

Suggestions?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/metosin/compojure-api/issues/322>, or mute the thread

**Comment by kanwei** [comment]
Thank you, that worked for me! Also, great job on the library, you guys are doing amazing work.

**Comment by ikitommi** [comment]
thanks!
