### ISSUE TITLE
Compojure-api does not print stack traces

### ISSUE THREAD

**Issue by bufferunderpants** [metosin/compojure-api#69]
Hello,

I don't know if there's a rationale for this, but the exception handlers defined in `compojure.api.middleware/handle-req-error`  don't print stack traces, and debugging from the rather laconic response body from requests is harder than it needs to be. I would suggest that a simple `(.printStackTrace e)` be added to the beginning of `handle-req-error` in order to help this.

**Comment by ikitommi** [comment]
Hi.

Isn't it already there?

https://github.com/metosin/compojure-api/blob/master/src/compojure/api/middleware.clj#L37

**Comment by bufferunderpants** [comment]
Silly me, it was already there, should have upgraded first, I guess. Anyway, that removes an awful `alter-var-root` from my codebase, so thank you.

**Comment by ikitommi** [comment]
your welcome :)

**Comment by ikitommi** [comment]
btw, we are publishing up all compojure-api options for easier customization in the client project (instead of `alter-var-root`ing).

See https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md#0180-232015 & https://github.com/metosin/compojure-api/blob/master/src/compojure/api/middleware.clj#L102-L149
